Pt 1258 bias value in past
rarible/protocol-contracts pull request #185
Opened 2022-09-28 13:20 UTC by disenotov

2022-09-28 14:55 UTC, evgenynacu requested changes

2022-09-28 14:55 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            brokenLine.slopeChanges.addToItem(lineStart, safeInt(line.slope));
2 вопроса. 1 - почему раньше не было этой строки? 2. точно в этой точке slope начнется? (А что если cliff)

2022-09-28 14:57 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            brokenLine.slopeChanges.addToItem(lineStart, safeInt(line.slope));
но вопрос 1 остается

2022-09-28 14:58 UTC, evgenynacu requested changes

2022-09-28 15:35 UTC, SKonstantinS commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            brokenLine.slopeChanges.addToItem(lineStart, safeInt(line.slope));
да ты правильно заметил, это только где нет клифа
там фишка в том, чтобы в истории сохранить в точке вызова функции add()  увеличение slope
когда я буду идти в прошлое, и дойду до этой точки я компенсирую initial.slope на величину, сохраненной в истории
пример:
неделя 1, initial.slope = 6
неделя 2 добалил лайн со slope = 3, тогда initial.slope = 6+3=9 , в историю неделя 2 -> +3
.....
неделя 256 приходит запрос: верни bias в точке неделя 1
в цикле с 256 до 1
.....
я в неделя 2  возьму из истории неделя 2 -> +3 , initial.slope = initial.slope - 3  этим я компенсирую initial.slope

2022-09-28 15:39 UTC, evgenynacu requested changes

2022-09-28 15:39 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +                time = time.add(1);
а тут правильно, что time стал меняться до действий? поменяется же все

2022-09-28 15:57 UTC, SKonstantinS commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +        uint256 finishTime = lineStart.add(period);
для уменьшения изменений нейминг можно вернуть
я подумал, что может надо нейминг такой-же как в функции remove()

2022-09-28 16:04 UTC, SKonstantinS commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +                time = time.add(1);
тут правильно, 
тк в функции add() в cliffEnd теперь сохраняется реальная точка
`uint cliffEnd = line.start.add(cliff);`
а раньше было 
uint cliffEnd = line.start.add(cliff).sub(1);
поэтому когда иду по времени вперед я сначала time++;
а потом корректирую slope,bias согласно истории

2022-09-29 10:35 UTC, evgenynacu requested changes

2022-09-29 10:35 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +                int newBias = safeInt(bias).add(brokenLine.biasChanges[time]);
А нам нужно вообще biasChanges тут смотреть? раньше не было и сейчас, кажется, не должно быть

2022-09-29 10:39 UTC, evgenynacu requested changes

2022-09-29 10:39 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            int newBias = safeInt(bias).add(brokenLine.biasChanges[time]); //
то же самое тут. biasChanges точно нужно смотреть, когда вперед идем?

2022-09-29 10:39 UTC, evgenynacu commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            slope = 0;
у нас тут раньше бага была, получается? раньше возвращали не 0

2022-09-29 10:56 UTC, SKonstantinS commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +                int newBias = safeInt(bias).add(brokenLine.biasChanges[time]);
согласен смысла нет, только зря тратим газ на чтение storadge

2022-09-29 11:03 UTC, SKonstantinS commented on staking/contracts/lib-broken-line/LibBrokenLine.sol
> +            slope = 0;
да не ноль
и это баг однозначно

2022-10-07 09:26 UTC, merged